### ISSUE TITLE
 Error: Class Illuminate\Foundation\Composer does not exist

### ISSUE THREAD

**Issue by sbrugman** [laralib/l5scaffold#29]
I get the following error when trying to scaffold (in Laravel version 5.2):

" Class Illuminate\Foundation\Composer does not exist"

The class is removed in this version of Laravel.

**Comment by sbrugman** [comment]
Can be fixed by using "use Illuminate\Support\Composer;" instead of the class named above for Laravel >= 5.2.

**Comment by gildniy** [comment]
So please let's not move quickly into L5.2.x, unless after each package installation, if need we search the use of that "Illuminate\Foundation\Composer" in any package using commands and replace it with "Illumination\Support\Composer" class and replace. It's what am doing while testing L5.2.x.
:1234:

**Comment by itsazzad** [comment]
@gildniy what was that?

**Comment by gildniy** [comment]
@itsazzad it's a problem caused by moving the Composer class from "Illuminate\Support\" in Laravel 5.1.x to "Illuminate\Foundation" Laravel 5.2.x,
With more explanation here is a post to deal with this:
http://stackoverflow.com/questions/34465721/laravel-5-1-to-5-2-upgrade-error

**Comment by Ouajjani** [comment]
thx for the tip folks.
but May i ask where exactly do we need to change 'Illuminate\Foundation\Composer' to  'Illuminate\Support\Composer' ?

**Comment by gildniy** [comment]
@Ouajjani in some few packages requiring that. I met this in "laracasts/generators" and "cviebrock/eloquent-sluggable" but you may meet this in other too!

**Comment by bfncs** [comment]
@Ouajjani The simplest *temporary* solution would be to do a recursive search of `Illuminate\Foundation\Composer` in your vendors directory and replace it with `Illuminate\Support\Composer` throughout your project, e.g. using find and sed:

    find . -type f -exec sed -i 's/Illuminate\\Foundation\\Composer/Illuminate\\Support\\Composer/g' {} +

Afterwards you'll have to wait for the needed changes being adopted by the package vendors.

**Comment by mankms** [comment]
Pull request submitted: #30.

**Comment by webbtj** [comment]
Just a suggestion but shouldn't this change warrant a minor release version instead of a patch? I think if you were to bring 5.2 support into a 1.1 release (instead of 1.0.4) it would be much clearer for users. As of now, for my 5.1 app I'm going to have to identify a specific patch version (1.0.3 or less). If you brought the 5.2 compatibility I could at least go with ~1.0 in case there are other patches to come in the 1.0 release. Just a thought, I know managing multiple releases is a pain, but it would at least give those still on 5.1 an option besides locking into a very specific patch that will never get updated and patching the code themselves.

**Comment by fernandobritofl** [comment]
this was fixed!
